apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cosmosmsi
  name: cosmosmsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosmsi
  template:
    metadata:
      labels:
        app: cosmosmsi
        aadpodidbinding: mongoidentity
    spec:
      containers:
      - image: acraccess.azurecr.io/cosmosmsi:latest
        name: cosmosmsi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: 
          requests:
            memory: 750Mi
            cpu: "0.5"
          limits:
            memory: 750Mi
            cpu: "0.5" 
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5    
        envFrom:
        - secretRef:
           name: vault-connect
            

