apiVersion: v1
kind: Service
metadata:
  labels:
    app: cosmosmsi
  name: cosmosmsi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cosmosmsi
  type: LoadBalancer

